/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ki4wangdy_tinyThread_FastLock */

#ifndef _Included_com_ki4wangdy_tinyThread_FastLock
#define _Included_com_ki4wangdy_tinyThread_FastLock
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ki4wangdy_tinyThread_FastLock
 * Method:    nativeId
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_ki4wangdy_tinyThread_FastLock_nativeId
  (JNIEnv *, jobject);

/*
 * Class:     com_ki4wangdy_tinyThread_FastLock
 * Method:    destoryNativeid
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_ki4wangdy_tinyThread_FastLock_destoryNativeid
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_ki4wangdy_tinyThread_FastLock
 * Method:    nativeLock
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_ki4wangdy_tinyThread_FastLock_nativeLock
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_ki4wangdy_tinyThread_FastLock
 * Method:    nativeUnLock
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_ki4wangdy_tinyThread_FastLock_nativeUnLock
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_ki4wangdy_tinyThread_FastLock
 * Method:    nativeTryLock
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_ki4wangdy_tinyThread_FastLock_nativeTryLock
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
