/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ki4wangdy_tinyThread_Thread */

#ifndef _Included_com_ki4wangdy_tinyThread_Thread
#define _Included_com_ki4wangdy_tinyThread_Thread
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ki4wangdy_tinyThread_Thread
 * Method:    nativeId
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_ki4wangdy_tinyThread_Thread_nativeId
  (JNIEnv *, jobject);

/*
 * Class:     com_ki4wangdy_tinyThread_Thread
 * Method:    destoryNativeId
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_ki4wangdy_tinyThread_Thread_destoryNativeId
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_ki4wangdy_tinyThread_Thread
 * Method:    nativeSleep
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_ki4wangdy_tinyThread_Thread_nativeSleep
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_ki4wangdy_tinyThread_Thread
 * Method:    nativeYield
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_ki4wangdy_tinyThread_Thread_nativeYield
  (JNIEnv *, jclass);

/*
 * Class:     com_ki4wangdy_tinyThread_Thread
 * Method:    nativeThreadId
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_ki4wangdy_tinyThread_Thread_nativeThreadId
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_ki4wangdy_tinyThread_Thread
 * Method:    nativeJoin
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_ki4wangdy_tinyThread_Thread_nativeJoin
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
